---
name: Env-Sanctify-Auto
version: 1.001
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: Perl module that cleans up %ENV
license: perl
resources:
  Ratings: http://cpanratings.perl.org/d/Env-Sanctify-Auto
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Env-Sanctify-Auto
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Env-Sanctify-Auto
requires:
  Carp: 1.04
  Env::Sanctify: 0
  perl: 5.006
  strict: 0
  version: 0.74
  warnings: 0
build_requires:
  Test::More: 0
  Test::NoWarnings: 0.084
dynamic_config: 0
provides:
  Env::Sanctify::Auto:
    file: lib/Env/Sanctify/Auto.pm
    version: 1.001
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
